### ISSUE TITLE
Cannot add custom Story Formats due to missing network permissions

### ISSUE THREAD

**Issue by SnoriPiper** [popey/twinejs-snap#1]
## Issue Description
The current Twinejs snap (v2.9.2) cannot add custom Story Formats due to missing network permissions. When attempting to add a Story Format, it times out with the error "The story format at this address could not be retrieved (Timeout)."

## Technical Details
- Twinejs version: 2.9.2 (snap revision 105)
- Ubuntu version: 24.04
- Error seen in system logs:
  - `apparmor="DENIED" operation="create" class="net" profile="snap.twinejs.twinejs"`
  - `apparmor="DENIED" operation="open" class="file" profile="snap.twinejs.twinejs" name="/etc/hosts"`
  - `apparmor="DENIED" operation="open" class="file" profile="snap.twinejs.twinejs" name="/run/systemd/resolve/stub-resolv.conf"`

## Requested Solution
Could you please add the following plugs to the snap configuration:
- network
- network-bind

These permissions are necessary for Twine to fetch Story Format files from external URLs.

## Steps to Reproduce
1. Open Twine
2. Click the Story Format button
3. Click "+ Add"
4. Enter any Story Format URL (e.g., http://www.maximumverbosity.net/twine/Illume/format.js)
5. Observe the timeout error

## Additional Notes
- The Story Format URLs are accessible via web browser
- The issue appears to be specifically related to the snap's network access permissions

**Comment by popey** [comment]
I only added network for now, because I don't _think_ it needs network-bind.
